### ISSUE TITLE
xpra: cannot find live server for display

### ISSUE THREAD

**Issue by pciavald** [kaueraal/run_scaled#15] opened 2018-10-22 23:50 UTC
Manjaro Linux / fresh install / nvidia non-free driver

```
[pciavald@macpro-manjaro paper]$ run_scaled --scale=0.5 google-chrome-beta
Warning: cannot use the system proxy for 'start' subcommand,
 failed to connect to '/run/xpra/system':
 [Errno 2] No such file or directory
 more information may be available in your system log
Entering daemon mode; any further errors will be reported to:
  /run/user/1000/xpra/:7435660.log
2018-10-23 01:44:11,289 Warning: zlib is the only compressor enabled
2018-10-23 01:44:11,289  install and enable lzo or lz4 support for better performance
2018-10-23 01:44:11,289 Xpra gtk2 client version 2.3.4-r20510 64-bit
2018-10-23 01:44:11,290  running on Linux ManjaroLinux 18.0.0-rc Illyria
2018-10-23 01:44:11,292 Warning: failed to import opencv:
2018-10-23 01:44:11,292  No module named cv2
2018-10-23 01:44:11,292  webcam forwarding is disabled
Warning: failed to import GStreamer 1.x:
 No module named gi
2018-10-23 01:44:12,045 Error: failed to query sound subsystem:
2018-10-23 01:44:12,045  query did not return any data
2018-10-23 01:44:13,201 No OpenGL_accelerate module loaded: No module named OpenGL_accelerate
2018-10-23 01:44:13,593 OpenGL enabled with GeForce GTX 1050 Ti/PCIe/SSE2
2018-10-23 01:44:13,594 Error setting up dbus signals:
2018-10-23 01:44:13,594  No module named dbus.mainloop.glib
2018-10-23 01:44:13,612 Error: printing disabled:
2018-10-23 01:44:13,613  No module named cups
xpra initialization error:
 cannot find live server for display :7435660
xpra initialization error:
 cannot find live server for display :7435660
```

Error is displayed on the terminal when starting apps (tried chrome, vscode). Chrome still starts but with the same resolution as standalone.

**Comment by adityajpatil** [comment] 2018-10-24 07:30
Same issue here,

> Warning: cannot use the system proxy for 'start' subcommand,
 failed to connect to '/run/xpra/system':
 [Errno 111] Connection refused
 more information may be available in your system log
Entering daemon mode; any further errors will be reported to:
  /run/user/1000/xpra/:72317770.log
2018-10-24 12:57:15,612 Xpra gtk2 client version 2.3.4-r20510 64-bit
2018-10-24 12:57:15,613  running on Linux ManjaroLinux 18.0.0-rc Illyria
2018-10-24 12:57:15,614 Warning: failed to import opencv:
2018-10-24 12:57:15,614  No module named cv2
2018-10-24 12:57:15,615  webcam forwarding is disabled
Warning: failed to import GStreamer 1.x:
 No module named gi
2018-10-24 12:57:16,145 Error: failed to query sound subsystem:
2018-10-24 12:57:16,145  query did not return any data
2018-10-24 12:57:16,948 No OpenGL_accelerate module loaded: No module named OpenGL_accelerate
2018-10-24 12:57:17,128 OpenGL enabled with Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)
2018-10-24 12:57:17,129 Error setting up dbus signals:
2018-10-24 12:57:17,129  No module named dbus.mainloop.glib
2018-10-24 12:57:17,132 Error: printing disabled:
2018-10-24 12:57:17,132  No module named cups
xpra initialization error:
 cannot find live server for display :72317770
xpra initialization error:
 cannot find live server for display :72317770

**Comment by cyberlis** [comment] 2018-10-24 12:50
`run_scaled --scale=0.5 --sleep=5 google-chrome-beta`

**Comment by cyberlis** [comment] 2018-10-24 12:52
> Manjaro Linux / fresh install / nvidia non-free driver
> 
> ```
> [pciavald@macpro-manjaro paper]$ run_scaled --scale=0.5 google-chrome-beta
> Warning: cannot use the system proxy for 'start' subcommand,
>  failed to connect to '/run/xpra/system':
>  [Errno 2] No such file or directory
>  more information may be available in your system log
> Entering daemon mode; any further errors will be reported to:
>   /run/user/1000/xpra/:7435660.log
> 2018-10-23 01:44:11,289 Warning: zlib is the only compressor enabled
> 2018-10-23 01:44:11,289  install and enable lzo or lz4 support for better performance
> 2018-10-23 01:44:11,289 Xpra gtk2 client version 2.3.4-r20510 64-bit
> 2018-10-23 01:44:11,290  running on Linux ManjaroLinux 18.0.0-rc Illyria
> 2018-10-23 01:44:11,292 Warning: failed to import opencv:
> 2018-10-23 01:44:11,292  No module named cv2
> 2018-10-23 01:44:11,292  webcam forwarding is disabled
> Warning: failed to import GStreamer 1.x:
>  No module named gi
> 2018-10-23 01:44:12,045 Error: failed to query sound subsystem:
> 2018-10-23 01:44:12,045  query did not return any data
> 2018-10-23 01:44:13,201 No OpenGL_accelerate module loaded: No module named OpenGL_accelerate
> 2018-10-23 01:44:13,593 OpenGL enabled with GeForce GTX 1050 Ti/PCIe/SSE2
> 2018-10-23 01:44:13,594 Error setting up dbus signals:
> 2018-10-23 01:44:13,594  No module named dbus.mainloop.glib
> 2018-10-23 01:44:13,612 Error: printing disabled:
> 2018-10-23 01:44:13,613  No module named cups
> xpra initialization error:
>  cannot find live server for display :7435660
> xpra initialization error:
>  cannot find live server for display :7435660
> ```
> Error is displayed on the terminal when starting apps (tried chrome, vscode). Chrome still starts but with the same resolution as standalone.

And chrome has its own flag `/usr/bin/google-chrome-stable --force-device-scale-factor=0.5`

**Comment by KylePiira** [comment] 2018-10-24 13:56
I am on Ubuntu 18.04 also experiencing this error. It does not appear that `--sleep` has any effect (tried values of 1, 5, 10, and 100). It looks like its just failing to start the server to begin with. 

Simply running `xpra start` on my system also produces the same error. 

```
Warning: cannot use the system proxy for 'start' subcommand,
 failed to connect to '/run/xpra/system':
 [Errno 2] No such file or directory

```

**Comment by HTY2003** [comment] 2018-10-29 03:30
I managed to solve this error by installing `xorg-server-xpra`, but it still doesn't work

**Comment by pandasauce** [comment] 2018-10-31 13:35
Also experiencing the same problem on 18.04.

```
Warning: cannot use the system proxy for 'start' subcommand,
 failed to connect to '/run/xpra/system':
 [Errno 2] No such file or directory
Entering daemon mode; any further errors will be reported to:
  /run/user/1000/xpra/:28318870.log
[...skip...]
InitException: cannot find any live servers to connect to
xpra initialization error:
 cannot find any live servers to connect to
```

This is what that log file says:

```
2018-10-31 13:31:44,116 Warning: xpra start from an existing 'ubuntu' desktop session
2018-10-31 13:31:44,117  pulseaudio forwarding may not work
2018-10-31 13:31:44,117  try using a clean environment, a dedicated user,
2018-10-31 13:31:44,117  or disable xpra's "pulseaudio" option
xpra main error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/xpra/scripts/main.py", line 177, in main
    return run_mode(script_file, err, options, args, mode, defaults)
  File "/usr/lib/python2.7/dist-packages/xpra/scripts/main.py", line 1424, in run_mode
    return run_server(error_cb, options, mode, script_file, args, current_display)
  File "/usr/lib/python2.7/dist-packages/xpra/scripts/server.py", line 648, in run_server
    xvfb, display_name = start_Xvfb(opts.xvfb, pixel_depth, display_name, cwd, uid, gid, xauth_data)
  File "/usr/lib/python2.7/dist-packages/xpra/server/vfb_util.py", line 159, in start_Xvfb
    stdin=subprocess.PIPE, preexec_fn=preexec)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by enovella** [comment] 2018-10-31 15:26
Same error on Ubuntu 18.04. Finding a solution at the moment.

**Comment by kaueraal** [comment] 2018-12-09 00:12
May be a duplicate of #12 .

**Comment by kaueraal** [comment] 2018-12-09 00:13
Does this issue persist?

**Comment by adityajpatil** [comment] 2018-12-11 06:33
> Does this issue persist?

Yes. Still getting the same issue.

**Comment by adityajpatil** [comment] 2019-01-25 17:07
Issue fixed for me.

As per the comment by @wohali , I looked at the log and installed the packages that were relevant to the error message. However, this might or might not be relevant to fixing the issue for me.

More importantly, what I found was that I needed to pass environment variables before ./run_scaled. Also, I needed to give --sleep option to let the wine application start. So instead of doing,

`./run_scaled  WINEPREFIX=/foo wine application_name`

I had to do
` WINEPREFIX=/foo ./run_scaled --sleep=20 wine application_name`


software that might help resolve some errors are,

> gst-python2
> python2-pycups
> python2-dbus
> xorg-server-xvfb
> xpra

@kaueraal Please fix the dependency list

**Comment by sopgenorth** [comment] 2019-04-11 06:28
I was able to fix this by installing xpra from the official site, instead of from the default Ubuntu sources. They don't have fantastic instructions though: https://xpra.org/trac/wiki/Download#Linux

**Comment by totaam** [comment] 2019-07-20 06:29
FYI: as of xpra v3, you don't have to sleep to connect to a socket [client to retry to connect until it succeeds
](https://www.xpra.org/trac/ticket/2346).

**Comment by semperos** [comment] 2019-07-22 23:09
Per @wohali on Fedora, install xvfb via:

```
sudo dnf install xorg-x11-server-Xvfb
```

This solved this issue for me.

**Comment by mackevinbraza** [comment] 2022-11-15 21:40
Hello folks, 

I am using run_scaled in my ubuntu with VMD and I am still experiencing this error. This occurred after I installed xpra. I'm curious if somebody else is experiencing this. Thanks in advance!

`(base) mbraza:run_scaled-master$ ./run_scaled vmd
Warning: cannot use the system proxy for 'start' subcommand,
 failed to connect to '/run/xpra/system':
 [Errno 2] No such file or directory
Entering daemon mode; any further errors will be reported to:
  /run/user/704015360/xpra/:26789853.log
2022-11-15 13:38:52,415 Xpra gtk2 client version 2.1.3-r17247M 64-bit
2022-11-15 13:38:52,415  running on Linux Ubuntu 18.04 bionic
2022-11-15 13:38:52,417 Warning: failed to import opencv:
2022-11-15 13:38:52,417  No module named cv2
2022-11-15 13:38:52,417  webcam forwarding is disabled
2022-11-15 13:38:53,603 GStreamer version 1.14.5 for Python 2.7.17 64-bit
2022-11-15 13:38:54,437 PyOpenGL warning: missing accelerate module
2022-11-15 13:38:54,600 OpenGL enabled with NVIDIA RTX A5000/PCIe/SSE2
2022-11-15 13:38:54,739 Error: printing disabled:
2022-11-15 13:38:54,739  No module named cups
InitException: cannot find any live servers to connect to
xpra initialization error:
 cannot find any live servers to connect to
InitException: cannot find any live servers to connect to
xpra initialization error:
 cannot find any live servers to connect to`

**Comment by totaam** [comment] 2022-11-16 08:42
> `Xpra gtk2 client version 2.1.3-r17247M 64-bit`

@mackevinbraza don't use outdated versions, please also see https://github.com/Xpra-org/xpra/wiki/Distribution-Packages

**Comment by kaueraal** [comment] 2023-07-22 20:41
Xpra directly includes an equivalent tool since [version 4.1](https://github.com/Xpra-org/xpra/blob/4d73c3644d6692bd51376296ed913f18a809f1a9/docs/CHANGELOG.md#41-2021-02-26). It is also called `run_scaled` and is part of [the default Xpra installation](https://github.com/Xpra-org/xpra/blob/master/fs/bin/run_scaled).

Hence, this script here is deprecated and no longer maintained. I'm sorry that it took me quite long to officially announce it here. Thank you for your support and please continue your HiDPI journey with Xpra's tool!

**Closed by kaueraal** 2023-07-22 20:41 UTC
